### ISSUE TITLE
Not able to render style in chrome

### ISSUE THREAD

**Issue by fasikk** [lantanagroup/stylesheets#6]
Having issues in chrome. Please see attached image.

error in chrome
![image](https://cloud.githubusercontent.com/assets/168743/22507221/6b8af6a0-e8a6-11e6-8302-1b28ce45a9f1.png)

working in firfox
![image](https://cloud.githubusercontent.com/assets/168743/22507232/773e508c-e8a6-11e6-9f6b-2a7d2930583d.png)

**Comment by EricParapini-Lantanagroup** [comment]
Hi, 

This is due to the way security works in Chrome. By default, chrome puts restrictions on local files. 
It seems to be related to this: https://blog.chromium.org/2008/12/security-in-depth-local-web-pages.html

If outputs are wanted with Chrome, there are two options. 

1) Perform an XML transformation and save the result as an html file. The resulting html file will have the style information embedded in it, and will display the rendering with no issues. 

2) Run chrome as: 
 `"C:\PathTo\Chrome.exe" --allow-file-access-from-files "C:\PathTo\CDAFile"`

For this to work, chrome can't be already running or running in the background when you execute the command.

Confirmed working with the following: 
Chrome: Version 55.0.2883.87 m (64-bit)
OS: Windows 10, 64-bit

Let me know if there's anything else I can help with

Most info was taken from this [stackoverflow question + answer](http://stackoverflow.com/questions/2981524/how-can-i-make-xslt-work-in-chrome/6251757#6251757). I tested the commands to ensure they still work today.
